import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')

function readProjectFile(path) {
  return readFileSync(resolve(rootDir, path), 'utf8')
}

test('Prisma schema models record-only referral tables without external reference models', () => {
  const schema = readProjectFile('prisma/schema.prisma')

  assert.match(schema, /model EmployeeShare/)
  assert.match(schema, /employeeId\s+String\s+@map\("employee_id"\)\s+@db\.VarChar/)
  assert.match(schema, /model EmployeeDownload/)
  assert.match(schema, /recieverEmpId\s+String\s+@map\("reciever_emp_id"\)\s+@db\.VarChar/)
  assert.match(schema, /os\s+String\s+@default\("unknown"\)\s+@db\.VarChar\(16\)/)
  assert.doesNotMatch(schema, /schemas\s*=/)
  assert.doesNotMatch(schema, /model ServiceUser/)
  assert.doesNotMatch(schema, /model HrEmployeeBasicInfo/)
  assert.doesNotMatch(schema, /userId/)
  assert.doesNotMatch(schema, /employeeName/)
  assert.doesNotMatch(schema, /pointBalance/)
  assert.doesNotMatch(schema, /receiverEmployee/)
  assert.doesNotMatch(schema, /verificationStatus/)
  assert.doesNotMatch(schema, /verifiedAt/)
  assert.doesNotMatch(schema, /@@index\(\[verificationStatus\]\)/)
})

test('migration removes external reference tables and dropped employee share fields', () => {
  const migration = readProjectFile('prisma/migrations/20260616000000_remove_reference_tables_and_share_fields/migration.sql')

  assert.match(migration, /DROP CONSTRAINT IF EXISTS "employee_download_reciever_emp_id_fkey"/)
  assert.match(migration, /DROP CONSTRAINT IF EXISTS "employee_share_user_id_fkey"/)
  assert.match(migration, /DROP CONSTRAINT IF EXISTS "employee_share_employee_id_fkey"/)
  assert.match(migration, /DROP COLUMN IF EXISTS "user_id"/)
  assert.match(migration, /DROP COLUMN IF EXISTS "employee_name"/)
  assert.match(migration, /DROP COLUMN IF EXISTS "point_balance"/)
  assert.match(migration, /DROP TABLE IF EXISTS "service_user"\."users"/)
  assert.match(migration, /DROP TABLE IF EXISTS "dbo"\."v_HR_EXP_EmpBasicInfo"/)
})

test('example data clears local sample rows without inserting mock data', () => {
  const seedPath = resolve(rootDir, 'prisma/example-data.sql')
  assert.equal(existsSync(seedPath), true)

  const seedSql = readFileSync(seedPath, 'utf8')
  assert.match(seedSql, /DELETE FROM "public"\."employee_download"/)
  assert.match(seedSql, /DELETE FROM "public"\."employee_share"/)
  assert.doesNotMatch(seedSql, /service_user/)
  assert.doesNotMatch(seedSql, /v_HR_EXP_EmpBasicInfo/)
  assert.doesNotMatch(seedSql, /INSERT INTO/)
  assert.doesNotMatch(seedSql, /EMP001/)
  assert.doesNotMatch(seedSql, /22222222-2222-4222-8222-222222222222/)
})

test('employee shares persist only the referrer employee ID', () => {
  const repository = readProjectFile('server/repositories/referralRepository.ts')
  const service = readProjectFile('server/services/referralService.ts')
  const utils = readProjectFile('server/utils/referral.ts')
  const sharedTypes = readProjectFile('shared/types/referral.ts')
  const entryPage = readProjectFile('pages/friend-get-friend/user_Id.vue')
  const qrPage = readProjectFile('pages/friend-get-friend/qr-code.vue')

  assert.match(repository, /export function findEmployeeShareByEmployeeId/)
  assert.match(repository, /export function createEmployeeShare/)
  assert.match(repository, /export function reactivateEmployeeShare/)
  assert.doesNotMatch(repository, /upsertServiceUserReference/)
  assert.doesNotMatch(repository, /upsertHrEmployeeReference/)
  assert.doesNotMatch(repository, /employeeName/)
  assert.doesNotMatch(repository, /pointBalance/)
  assert.match(service, /findEmployeeShareByEmployeeId\(tx, input\.employeeId\)/)
  assert.match(service, /reactivateEmployeeShare\(tx, existingShare\.id, input\)/)
  assert.match(service, /createEmployeeShare\(tx, input\)/)
  assert.doesNotMatch(service, /upsertServiceUserReference/)
  assert.doesNotMatch(service, /upsertHrEmployeeReference/)
  assert.doesNotMatch(utils, /getEmployeeDisplayName/)
  assert.doesNotMatch(sharedTypes, /userId:\s*string/)
  assert.doesNotMatch(sharedTypes, /employeeName:\s*string/)
  assert.doesNotMatch(sharedTypes, /pointBalance/)
  assert.doesNotMatch(readProjectFile('shared/schemas/referral.ts'), /userIdSchema/)
  assert.doesNotMatch(readProjectFile('shared/schemas/referral.ts'), /employeeNameSchema/)
  assert.doesNotMatch(readProjectFile('shared/schemas/referral.ts'), /pointBalanceSchema/)
  assert.doesNotMatch(entryPage, /userId:/)
  assert.doesNotMatch(entryPage, /employeeName:/)
  assert.doesNotMatch(entryPage, /pointBalance:/)
  assert.doesNotMatch(qrPage, /userId:/)
  assert.doesNotMatch(qrPage, /employeeName:/)
  assert.doesNotMatch(qrPage, /pointBalance:/)
})

test('download recording does not create employee shares for receiver users', () => {
  const repository = readProjectFile('server/repositories/referralRepository.ts')
  const service = readProjectFile('server/services/referralService.ts')

  assert.doesNotMatch(repository, /export function upsertServiceUserReference/)
  assert.doesNotMatch(repository, /export function upsertHrEmployeeReference/)
  assert.doesNotMatch(service, /ensureEmployeeShareForVerifiedReceiver/)
  assert.doesNotMatch(service, /findServiceUserByEmployeeId/)
  assert.doesNotMatch(service, /ensureReceiverShare/)
  assert.doesNotMatch(service, /upsertHrEmployeeReference\(tx/)
  assert.doesNotMatch(service, /findHrEmployeeByEmpId\(tx, input\.recieverEmpId\)/)
  assert.doesNotMatch(service, /Receiver employee ID was not found\./)
  assert.match(service, /export async function createOrUpdateEmployeeShare/)
  assert.match(service, /return createEmployeeShare\(tx, input\)/)
  assert.ok(
    service.indexOf('export async function createOrUpdateEmployeeShare') <
      service.indexOf('return createEmployeeShare(tx, input)'),
    'employee_share should be created only through the employee-share API service path'
  )
  assert.ok(
    service.indexOf('export async function recordEmployeeDownload') >
      service.indexOf('return createEmployeeShare(tx, input)'),
    'recordEmployeeDownload should not create employee_share rows for receivers'
  )
})

test('download service rejects referrers submitting their own employee ID', () => {
  const service = readProjectFile('server/services/referralService.ts')
  const selfReferralGuard = /share\.employeeId\.trim\(\)\.toUpperCase\(\)\s*===\s*input\.recieverEmpId\.trim\(\)\.toUpperCase\(\)/

  assert.match(service, selfReferralGuard)
  assert.match(service, /Referrer cannot submit their own employee ID\./)
  assert.ok(
    service.indexOf('Referrer cannot submit their own employee ID.') <
      service.indexOf('return await createEmployeeDownload(tx, input)'),
    'self-referral guard must run before creating employee_download'
  )
})

test('download service keeps receiver employee IDs unique across referral shares', () => {
  const service = readProjectFile('server/services/referralService.ts')
  const repository = readProjectFile('server/repositories/referralRepository.ts')
  const migration = readProjectFile('prisma/migrations/20260607000000_unique_active_receiver_download/migration.sql')

  assert.match(repository, /export function findActiveEmployeeDownloadByReceiver/)
  assert.match(repository, /where:\s*\{[\s\S]*recieverEmpId,[\s\S]*\.\.\.activeRecord[\s\S]*\}/)
  assert.match(service, /findActiveEmployeeDownloadByReceiver\(tx, input\.recieverEmpId\)/)
  assert.match(service, /existingDownload\.employeeShareId !== input\.employeeShareId/)
  assert.match(service, /This employee ID has already been submitted for another referral\./)
  assert.ok(
    service.indexOf('findActiveEmployeeDownloadByReceiver(tx, input.recieverEmpId)') <
      service.indexOf('return await createEmployeeDownload(tx, input)'),
    'global receiver duplicate guard must run before creating employee_download'
  )
  assert.match(migration, /row_number\(\) OVER \([\s\S]*PARTITION BY "reciever_emp_id"/)
  assert.match(migration, /CREATE UNIQUE INDEX "employee_download_active_reciever_emp_id_key"/)
  assert.match(migration, /WHERE "deleted_at" IS NULL/)
})

test('shareapp referral route exists under the friend-get-friend Nuxt route path', () => {
  const shareappRoutePath = resolve(rootDir, 'pages/friend-get-friend/shareapp/[shareId].vue')
  const legacyRoutePath = resolve(rootDir, 'pages/friend-get-friend/[...slug].vue')
  const legacyRedirectMiddlewarePath = resolve(rootDir, 'server/middleware/legacyFriendGetFriendRoutes.ts')
  const nestedShareappRoutePath = resolve(rootDir, 'pages/share/shareapp/[shareId].vue')
  const rootRedirectPage = readProjectFile('pages/index.vue')

  assert.equal(existsSync(shareappRoutePath), true)
  assert.equal(existsSync(legacyRoutePath), false)
  assert.equal(existsSync(legacyRedirectMiddlewarePath), false)
  assert.equal(existsSync(nestedShareappRoutePath), false)
  assert.match(readProjectFile('server/utils/referral.ts'), /\/friend-get-friend\/shareapp\/\$\{employeeShareId\}/)
  assert.match(rootRedirectPage, /navigateTo\(["']\/friend-get-friend\/user_Id["']/)
})

test('first page checks manual employee IDs before routing to the QR page', () => {
  const entryPage = readProjectFile('pages/friend-get-friend/user_Id.vue')
  const qrPage = readProjectFile('pages/friend-get-friend/qr-code.vue')
  const checkUserApi = readProjectFile('server/api/friend-get-friend/check-user.ts')
  const enLocale = readProjectFile('i18n/locales/en.json')
  const thLocale = readProjectFile('i18n/locales/th.json')

  assert.equal(existsSync(resolve(rootDir, 'pages/friend-get-friend/qr-code.vue')), true)
  assert.match(entryPage, /const router = useRouter\(\)/)
  assert.match(entryPage, /const isCreatingShare = ref\(false\)/)
  assert.match(entryPage, /const referrerEmployeeId = ref\(["']["']\)/)
  assert.match(entryPage, /\.toUpperCase\(\)/)
  assert.match(entryPage, /const normalizedReferrerEmployeeId = computed/)
  assert.match(entryPage, /type CheckUserResponse =/)
  assert.match(entryPage, /type GetEmployeeShareResponse =/)
  assert.match(entryPage, /async function submitReferrerEmployeeId\(\)/)
  assert.match(entryPage, /if \(isCreatingShare\.value\) \{[\s\S]*return/)
  assert.match(entryPage, /isCreatingShare\.value = true/)
  assert.match(entryPage, /isCreatingShare\.value = false/)
  assert.match(entryPage, /key: ["']qrPage\.errors\.enterEmployeeId["']/)
  assert.match(entryPage, /const checkUserUrl = ["']\/api\/friend-get-friend\/check-user["']/)
  assert.match(entryPage, /\$fetch<CheckUserResponse>\(\s*checkUserUrl/)
  assert.match(entryPage, /employee_id:\s*normalizedReferrerEmployeeId\.value/)
  assert.match(entryPage, /\$fetch<GetEmployeeShareResponse>\(\s*["']\/api\/employee-shares["']/)
  assert.match(entryPage, /employeeId:\s*response\.data\.employee_id/)
  assert.match(entryPage, /path:\s*["']\/friend-get-friend\/qr-code["']/)
  assert.match(entryPage, /employeeShareId:\s*share\.id/)
  assert.match(entryPage, /v-model\.trim="referrerEmployeeId"/)
  assert.match(entryPage, /:disabled="isCreatingShare"/)
  assert.match(entryPage, /:aria-busy="isCreatingShare"/)
  assert.match(entryPage, /@submit\.prevent="submitReferrerEmployeeId"/)
  assert.match(entryPage, /qrPage\.referrer\.title/)
  assert.match(entryPage, /qrPage\.referrer\.subtitle/)
  assert.match(entryPage, /qrPage\.referrer\.action/)
  assert.match(entryPage, /qrPage\.referrer\.checking/)
  assert.match(entryPage, /qrPage\.referrer\.checkingTitle/)
  assert.match(entryPage, /qrPage\.referrer\.checkingDescription/)
  assert.match(entryPage, /v-if="isCreatingShare"/)
  assert.match(entryPage, /role="status"/)
  assert.doesNotMatch(entryPage, /navigateTo\(/)
  assert.doesNotMatch(entryPage, /router\.replace\(/)
  assert.doesNotMatch(entryPage, /employeeShareIdFromQuery/)
  assert.doesNotMatch(entryPage, /route\.query\.employee_id/)
  assert.doesNotMatch(entryPage, /import QRCode from ["']qrcode["']/)
  assert.doesNotMatch(entryPage, /async function loadShareQrByEmployeeId/)

  assert.match(qrPage, /const route = useRoute\(\)/)
  assert.match(qrPage, /import QRCode from ["']qrcode["']/)
  assert.match(qrPage, /const employeeShareIdFromQuery = computed/)
  assert.match(qrPage, /route\.query\.employeeShareId/)
  assert.match(qrPage, /type GetEmployeeShareResponse =/)
  assert.match(qrPage, /async function loadShareQrById\(employeeShareId: string\)/)
  assert.match(qrPage, /\$fetch<GetEmployeeShareResponse>\(\s*`\/api\/shares\/\$\{encodeURIComponent\(employeeShareId\)\}`/)
  assert.match(qrPage, /await renderShareQr\(share\)/)
  assert.match(qrPage, /watch\(\s*employeeShareIdFromQuery/)
  assert.match(qrPage, /void loadShareQrById\(employeeShareId\)/)
  assert.match(qrPage, /t\(["']qrPage\.status\.loading["']\)/)
  assert.match(qrPage, /to=["']\/friend-get-friend\/user_Id["']/)
  assert.doesNotMatch(qrPage, /const employeeIdFromQuery = computed/)
  assert.doesNotMatch(qrPage, /route\.query\.employee_id/)
  assert.doesNotMatch(qrPage, /type CheckUserResponse =/)
  assert.doesNotMatch(qrPage, /\$fetch<CheckUserResponse>/)
  assert.doesNotMatch(qrPage, /\$fetch<GetEmployeeShareResponse>\(\s*["']\/api\/employee-shares["']/)
  assert.doesNotMatch(qrPage, /async function loadShareQrByEmployeeId/)
  assert.doesNotMatch(qrPage, /v-model="referrerEmployeeId"/)
  assert.doesNotMatch(qrPage, /@submit\.prevent="submitReferrerEmployeeId"/)
  assert.match(enLocale, /"referrer"/)
  assert.match(enLocale, /"enterEmployeeId"/)
  assert.match(enLocale, /"checkingTitle"/)
  assert.match(enLocale, /"checkingDescription"/)
  assert.match(thLocale, /"referrer"/)
  assert.match(thLocale, /"enterEmployeeId"/)
  assert.match(thLocale, /"checkingTitle"/)
  assert.match(thLocale, /"checkingDescription"/)
  assert.match(checkUserApi, /employeeIdSchema/)
  assert.match(checkUserApi, /query\.employee_id/)
  assert.match(checkUserApi, /employee_id:\s*employeeId/)
  assert.match(checkUserApi, /username:\s*employeeId/)
  assert.match(checkUserApi, /type_account:\s*["']user["']/)
  assert.doesNotMatch(checkUserApi, /createHash/)
  assert.doesNotMatch(checkUserApi, /buildLocalUserId/)
  assert.doesNotMatch(checkUserApi, /point_balance/)
  assert.doesNotMatch(checkUserApi, /employee_info/)
  assert.doesNotMatch(checkUserApi, /findServiceUserByEmployeeId/)
  assert.doesNotMatch(checkUserApi, /Employee ID was not found\./)
  assert.doesNotMatch(checkUserApi, /User was not found\./)
  assert.doesNotMatch(entryPage, /Create referral QR/)
  assert.doesNotMatch(entryPage, /User ID/)
  assert.doesNotMatch(entryPage, /Create QR/)
  assert.doesNotMatch(entryPage, /normalizedUserId/)
  assert.doesNotMatch(entryPage, /normalizedEmployeeId/)
  assert.doesNotMatch(qrPage, /Create referral QR/)
  assert.doesNotMatch(qrPage, /User ID/)
  assert.doesNotMatch(qrPage, /Create QR/)
  assert.doesNotMatch(qrPage, /normalizedUserId/)
  assert.doesNotMatch(qrPage, /normalizedEmployeeId/)

  const packageJson = JSON.parse(readProjectFile('package.json'))
  assert.equal(packageJson.dependencies.qrcode, '^1.5.4')
  assert.equal(packageJson.devDependencies['@types/qrcode'], '^1.5.6')
})

test('public referral APIs apply per-client rate limits', () => {
  const rateLimit = readProjectFile('server/utils/rateLimit.ts')
  const checkUserApi = readProjectFile('server/api/friend-get-friend/check-user.ts')
  const employeeSharesApi = readProjectFile('server/api/employee-shares.post.ts')
  const downloadsApi = readProjectFile('server/api/downloads.post.ts')
  const sharesApi = readProjectFile('server/api/shares/[shareId].get.ts')
  const employeesApi = readProjectFile('server/api/employees/[employeeId].get.ts')

  assert.match(rateLimit, /export function assertRateLimit/)
  assert.match(rateLimit, /getRequestHeader\(event, ['"]x-forwarded-for['"]\)/)
  assert.match(rateLimit, /X-RateLimit-Limit/)
  assert.match(rateLimit, /Retry-After/)
  assert.match(rateLimit, /statusCode:\s*429/)
  assert.match(rateLimit, /Too many requests\. Please try again later\./)
  assert.match(checkUserApi, /assertRateLimit\(event,\s*\{[\s\S]*keyPrefix:\s*["']check-user["'][\s\S]*limit:\s*30[\s\S]*windowMs:\s*60_000/)
  assert.match(employeeSharesApi, /assertRateLimit\(event,\s*\{[\s\S]*keyPrefix:\s*["']employee-shares["'][\s\S]*limit:\s*20[\s\S]*windowMs:\s*60_000/)
  assert.match(downloadsApi, /assertRateLimit\(event,\s*\{[\s\S]*keyPrefix:\s*["']downloads["'][\s\S]*limit:\s*60[\s\S]*windowMs:\s*60_000/)
  assert.match(sharesApi, /assertRateLimit\(event,\s*\{[\s\S]*keyPrefix:\s*["']shares["'][\s\S]*limit:\s*120[\s\S]*windowMs:\s*60_000/)
  assert.match(employeesApi, /assertRateLimit\(event,\s*\{[\s\S]*keyPrefix:\s*["']employees["'][\s\S]*limit:\s*120[\s\S]*windowMs:\s*60_000/)
})

test('share page opens the download popup instead of navigating to the download page', () => {
  const sharePage = readProjectFile('pages/friend-get-friend/shareapp/[shareId].vue')

  assert.doesNotMatch(sharePage, /path:\s*["']\/download["']/)
  assert.doesNotMatch(sharePage, /receiverEmployeeFound:/)
  assert.doesNotMatch(sharePage, /receiverName:/)
  assert.match(sharePage, /const showDownloadDialog = ref\(false\)/)
  assert.match(sharePage, /const hasStartedDownload = ref\(false\)/)
  assert.match(sharePage, /showDownloadDialog\.value = true/)
  assert.match(sharePage, /v-if="showDownloadDialog"/)
  assert.match(sharePage, /if \(hasStartedDownload\.value\) \{\s*return;?\s*\}/)
  assert.match(sharePage, /hasStartedDownload\.value = true/)
  assert.match(sharePage, /v-if="!hasStartedDownload"/)
  assert.match(sharePage, /\$fetch\(["']\/api\/downloads["']/)
  assert.match(sharePage, /method:\s*["']POST["']/)
  assert.match(sharePage, /employeeShareId:\s*shareId\.value/)
  assert.match(sharePage, /recieverEmpId:\s*downloadReceiverEmpId\.value/)
  assert.match(sharePage, /@click="downloadApp"/)
  assert.match(sharePage, /config\.public\.downloadUrl/)
  assert.match(sharePage, /window\.open\(url, ["']_blank["']\)/)
  assert.match(sharePage, /downloadWindow\.opener = null/)
  assert.match(sharePage, /function detectDeviceOs\(\): DownloadOs/)
  assert.match(sharePage, /function getDownloadOs\(\): DownloadOs/)
  assert.match(sharePage, /downloadStep\.value === ["']ios["'] \|\| downloadStep\.value === ["']android["']/)
  assert.match(sharePage, /const detectedOs = getDownloadOs\(\)/)
  assert.match(sharePage, /os:\s*detectedOs/)
  assert.match(sharePage, /downloadStep\.value = detectedOs === ["']unknown["'] \? ["']choose-os["'] : detectedOs/)
  assert.doesNotMatch(sharePage, /window\.location\.href = url/)
})

test('download records include detected OS', () => {
  const schema = readProjectFile('shared/schemas/referral.ts')
  const migration = readProjectFile('prisma/migrations/20260604000000_add_download_os/migration.sql')
  const repository = readProjectFile('server/repositories/referralRepository.ts')
  const downloadPage = readProjectFile('pages/friend-get-friend/download.vue')
  const adminPage = readProjectFile('pages/friend-get-friend/admin.vue')
  const adminService = readProjectFile('server/services/adminDashboardService.ts')
  const referralService = readProjectFile('server/services/referralService.ts')

  assert.match(schema, /downloadOsSchema = z\.enum\(\['ios', 'android', 'unknown'\]\)/)
  assert.match(schema, /os:\s*downloadOsSchema\.default\('unknown'\)/)
  assert.match(migration, /ADD COLUMN "os" varchar\(16\) NOT NULL DEFAULT 'unknown'/)
  assert.match(repository, /os:\s*string/)
  assert.match(repository, /updateEmployeeDownloadOs/)
  assert.match(referralService, /existingDownload\.os === ["']unknown["'] && input\.os !== ["']unknown["']/)
  assert.match(downloadPage, /function detectDeviceOs\(\): DownloadOs/)
  assert.match(downloadPage, /os:\s*detectedOs/)
  assert.match(adminService, /os:\s*download\.os/)
  assert.match(adminPage, /<th class="w-24 px-3 py-4">OS<\/th>/)
  assert.match(adminPage, /formatOs\(row\.os\)/)
})

test('download page reads the public download URL from runtime config', () => {
  const nuxtConfig = readProjectFile('nuxt.config.ts')
  const envExample = readProjectFile('.env.example')
  const downloadPage = readProjectFile('pages/friend-get-friend/download.vue')
  const sharePage = readProjectFile('pages/friend-get-friend/shareapp/[shareId].vue')

  assert.match(nuxtConfig, /downloadUrl:\s*process\.env\.NUXT_PUBLIC_DOWNLOAD_URL/)
  assert.match(envExample, /NUXT_PUBLIC_DOWNLOAD_URL=/)
  assert.match(downloadPage, /config\.public\.downloadUrl/)
  assert.doesNotMatch(downloadPage, /config\.public\.DownloadUrl/)
  assert.match(sharePage, /config\.public\.downloadUrl/)
})

test('share page lets receivers enter employee ID freely before download', () => {
  const sharePage = readProjectFile('pages/friend-get-friend/shareapp/[shareId].vue')
  const enLocale = readProjectFile('i18n/locales/en.json')
  const thLocale = readProjectFile('i18n/locales/th.json')

  assert.match(sharePage, /downloadReceiverEmpId\.value = normalizedEmployeeId\.value/)
  assert.match(sharePage, /recieverEmpId:\s*downloadReceiverEmpId\.value/)
  assert.match(sharePage, /\[400, 404, 409\]\.includes\(getStatusCode\(recordError\)\)/)
  assert.doesNotMatch(sharePage, /receiverEmployeeFound/)
  assert.doesNotMatch(sharePage, /receiverName/)
  assert.doesNotMatch(sharePage, /EmployeeLookupResponse/)
  assert.doesNotMatch(sharePage, /receiverLookupStatus/)
  assert.doesNotMatch(sharePage, /downloadReceiverEmployee/)
  assert.doesNotMatch(sharePage, /\/api\/employees\/\$\{encodeURIComponent/)
  assert.match(sharePage, /:placeholder="t\('shareApp\.employeeId\.placeholder'\)"/)
  assert.match(sharePage, /v-model\.trim="employeeId"/)
  assert.match(sharePage, /watch\(employeeId/)
  assert.doesNotMatch(sharePage, /employeeLookupDelayMs/)
  assert.doesNotMatch(sharePage, /employeeLookupTimeout/)
  assert.doesNotMatch(sharePage, /lookupEmployeeById/)

  assert.match(sharePage, /const isSelfReferral = computed/)
  assert.match(sharePage, /downloadReceiverEmpId\.value === referrerEmployeeId/)
  assert.match(sharePage, /shareApp\.selfReferral\.title/)
  assert.match(sharePage, /shareApp\.selfReferral\.description/)
  assert.match(sharePage, /shareApp\.selfReferral\.edit/)
  assert.match(sharePage, /v-if="isSelfReferral"[\s\S]*role="alert"/)
  assert.match(sharePage, /border-amber-400 bg-amber-100/)
  assert.match(sharePage, /async function editEmployeeId\(\)/)
  assert.match(sharePage, /downloadReceiverEmpId\.value = ["']{2}/)
  assert.match(sharePage, /employeeId\.value = ["']{2}/)
  assert.match(sharePage, /@click="editEmployeeId"/)
  assert.match(enLocale, /The referrer and referee are the same person/)
  assert.match(thLocale, /พบว่าผู้รับการแนะนำและผู้แนะนำเป็นบุคคลเดียวกัน/)
})

test('local PostgreSQL setup exists for Prisma Studio', () => {
  const composePath = resolve(rootDir, 'docker-compose.yml')
  const initPath = resolve(rootDir, 'prisma/local-reference-schema.sql')
  assert.equal(existsSync(composePath), true)
  assert.equal(existsSync(initPath), true)

  const packageJson = JSON.parse(readProjectFile('package.json'))
  assert.equal(packageJson.scripts['db:up'], 'docker compose up -d --wait postgres')
  assert.equal(packageJson.scripts['db:setup'], 'npm run db:up && npm run prisma:push && npm run db:seed')
  assert.equal(packageJson.scripts['db:studio'], 'prisma studio')
  assert.equal(packageJson.scripts['dev:clean'], 'nuxt cleanup && nuxt dev')
})

test('admin dashboard reads real download records and shows downloaded at', () => {
  const adminPage = readProjectFile('pages/friend-get-friend/admin.vue')
  const adminApi = readProjectFile('server/api/admin/dashboard.get.ts')
  const adminCsvApi = readProjectFile('server/api/admin/downloads.csv.get.ts')
  const adminService = readProjectFile('server/services/adminDashboardService.ts')
  const repository = readProjectFile('server/repositories/referralRepository.ts')

  assert.match(adminApi, /getAdminDashboard/)
  assert.match(adminApi, /getQuery\(event\)/)
  assert.match(adminApi, /getQueryOs/)
  assert.match(adminApi, /search:\s*getQueryString\(query\.search\)/)
  assert.match(adminApi, /os:\s*getQueryOs\(query\.os\)/)
  assert.match(adminApi, /dateFrom:\s*getQueryString\(query\.dateFrom\)/)
  assert.match(adminApi, /dateTo:\s*getQueryString\(query\.dateTo\)/)
  assert.doesNotMatch(adminApi, /verificationStatus/)
  assert.match(adminCsvApi, /getAdminDownloadsCsv/)
  assert.match(adminCsvApi, /Content-Type', 'text\/csv; charset=utf-8'/)
  assert.match(adminCsvApi, /Content-Disposition', 'attachment; filename="downloads\.csv"'/)
  assert.doesNotMatch(adminCsvApi, /verificationStatus/)
  assert.match(adminPage, /useFetch<AdminDashboardResponse>\(["']\/api\/admin\/dashboard["']/)
  assert.match(adminPage, /currentPage = ref\(1\)/)
  assert.match(adminPage, /const debouncedSearchQuery = ref\(["']["']\)/)
  assert.match(adminPage, /let searchDebounceTimer/)
  assert.match(adminPage, /const osFilter = ref/)
  assert.match(adminPage, /const dateFromFilter = ref/)
  assert.match(adminPage, /const dateToFilter = ref/)
  assert.match(adminPage, /const showWinnersDialog = ref\(false\)/)
  assert.match(adminPage, /const winnerSort = ref<["']highest["'] \| ["']lowest["']>\(["']highest["']\)/)
  assert.match(adminPage, /const winnerPage = ref\(1\)/)
  assert.match(adminPage, /const winnerPageSize = 10/)
  assert.match(adminPage, /recordedReceivers: number/)
  assert.match(adminPage, /activeReferrers: number/)
  assert.match(adminPage, /Total Downloads/)
  assert.match(adminPage, /Recorded Receivers/)
  assert.match(adminPage, /Active Referrers/)
  assert.match(adminPage, /Top 38/)
  assert.match(adminPage, /md:grid-cols-2 xl:grid-cols-4/)
  assert.match(adminPage, /const dashboardQuery = computed/)
  assert.match(adminPage, /query:\s*dashboardQuery/)
  assert.match(adminPage, /watch:\s*false/)
  assert.match(adminPage, /search:\s*debouncedSearchQuery\.value\.trim\(\) \|\| undefined/)
  assert.match(adminPage, /os:\s*osFilter\.value === ["']all["'] \? undefined : osFilter\.value/)
  assert.doesNotMatch(adminPage, /verificationStatusFilter/)
  assert.doesNotMatch(adminPage, /verificationStatus:/)
  assert.match(adminPage, /dateFrom:\s*dateFromFilter\.value \|\| undefined/)
  assert.match(adminPage, /dateTo:\s*dateToFilter\.value \|\| undefined/)
  assert.match(adminPage, /function refreshDashboard\(\)/)
  assert.match(adminPage, /watch\(searchQuery/)
  assert.match(adminPage, /setTimeout\(\(\) => \{[\s\S]*debouncedSearchQuery\.value = value[\s\S]*\}, 350\)/)
  assert.match(adminPage, /watch\(\s*\[debouncedSearchQuery,\s*osFilter,\s*dateFromFilter,\s*dateToFilter\]/)
  assert.match(adminPage, /onBeforeUnmount/)
  assert.match(adminPage, /watch\(currentPage/)
  assert.match(adminPage, /refreshDashboard\(\)/)
  assert.match(adminPage, /function resetFilters\(\)/)
  assert.match(adminPage, /function exportCsv\(\)/)
  assert.match(adminPage, /function escapeClientCsvValue/)
  assert.match(adminPage, /function downloadClientCsv/)
  assert.match(adminPage, /function exportWinnersCsv\(\)/)
  assert.match(adminPage, /top-38-pioneers\.csv/)
  assert.match(adminPage, /score: number/)
  assert.match(adminPage, /\[["']Rank["'], ["']Referrer Name["'], ["']Referrer Employee ID["'], ["']Refers["'], ["']Score["']\]/)
  assert.match(adminPage, /new URLSearchParams\(\)/)
  assert.match(adminPage, /window\.location\.href = `\/api\/admin\/downloads\.csv/)
  assert.match(adminPage, /function openWinnersDialog\(\)/)
  assert.match(adminPage, /function closeWinnersDialog\(\)/)
  assert.match(adminPage, /const sortedWinnerRows = computed/)
  assert.match(adminPage, /\[\.\.\.pioneers\.value\]\.sort/)
  assert.match(adminPage, /winnerSort\.value === ["']highest["']\s*\?\s*-referDifference\s*:\s*referDifference/)
  assert.match(adminPage, /firstPioneer\.rank - secondPioneer\.rank/)
  assert.match(adminPage, /secondPioneer\.rank - firstPioneer\.rank/)
  assert.match(adminPage, /const paginatedWinnerRows = computed/)
  assert.match(adminPage, /const winnerPageCount = computed/)
  assert.match(adminPage, /function goToPreviousWinnerPage\(\)/)
  assert.match(adminPage, /function goToNextWinnerPage\(\)/)
  assert.match(adminPage, /v-model="osFilter"/)
  assert.doesNotMatch(adminPage, /v-model="verificationStatusFilter"/)
  assert.doesNotMatch(adminPage, /All Status/)
  assert.doesNotMatch(adminPage, /Verified/)
  assert.doesNotMatch(adminPage, /Unverified/)
  assert.match(adminPage, /v-model="dateFromFilter"/)
  assert.match(adminPage, /v-model="dateToFilter"/)
  assert.match(adminPage, /@click="exportCsv"/)
  assert.match(adminPage, /v-model="winnerSort"/)
  assert.match(adminPage, /@click="exportWinnersCsv"/)
  assert.match(adminPage, /Highest first/)
  assert.match(adminPage, /Lowest first/)
  assert.match(adminPage, /@click="openWinnersDialog"/)
  assert.match(adminPage, /v-if="showWinnersDialog"/)
  assert.match(adminPage, /role="dialog"/)
  assert.match(adminPage, /Top 38 Pioneers/)
  assert.match(adminPage, /View All 38 Pioneers/)
  assert.match(adminPage, /v-for="pioneer in paginatedWinnerRows"/)
  assert.match(adminPage, /\{\{ pioneer\.rank \}\}/)
  assert.match(adminPage, /pioneer\.refers/)
  assert.match(adminPage, /pioneer\.score/)
  assert.match(adminPage, /numberFormatter\.format\(pioneer\.score\)/)
  assert.match(adminPage, /`winner-\$\{pioneer\.employeeId\}`/)
  assert.match(adminPage, /Page\s*\{\{ winnerPage \}\} of\s*\{\{ winnerPageCount \}\}/)
  assert.match(adminPage, /@click="goToPreviousWinnerPage"/)
  assert.match(adminPage, /@click="goToNextWinnerPage"/)
  assert.match(adminPage, /goToNextPage/)
  assert.match(adminPage, /Page\s*\{\{ pagination\.page \}\} of\s*\{\{ pagination\.pageCount \}\}/)
  assert.match(adminPage, /Downloaded At/)
  assert.match(adminPage, /formatDownloadedAt\(row\.downloadedAt\)/)
  assert.match(adminPage, />OS<\/th>/)
  assert.doesNotMatch(adminPage, /Share Code/)
  assert.doesNotMatch(adminPage, />Type</)
  assert.doesNotMatch(adminPage, /row\.shareCode/)
  assert.doesNotMatch(adminPage, /row\.type/)
  assert.match(adminService, /function buildDownloadWhere/)
  assert.match(adminService, /containsSearch/)
  assert.doesNotMatch(adminService, /verificationStatus/)
  assert.doesNotMatch(adminService, /function getVerificationStatusWhere/)
  assert.match(adminService, /parseBangkokDateStart/)
  assert.match(adminService, /countActiveEmployeeDownloads\(prisma, downloadWhere\)/)
  assert.match(adminService, /const campaignStatsWhere/)
  assert.doesNotMatch(adminService, /const verifiedCampaignStatsWhere/)
  assert.match(adminService, /groupActiveEmployeeDownloadsByReceiver\(prisma, campaignStatsWhere\)/)
  assert.match(adminService, /recordedReferrals:\s*totalDownloads/)
  assert.match(adminService, /recordedReceivers:\s*campaignReceivers\.length/)
  assert.match(adminService, /activeReferrers:\s*downloadsByShare\.length/)
  assert.match(adminService, /groupActiveEmployeeDownloadsByShare\(prisma, downloadWhere\)/)
  assert.match(adminService, /const leaderboardWhere/)
  assert.match(adminService, /groupActiveEmployeeDownloadsByShare\(prisma, leaderboardWhere\)/)
  assert.match(adminService, /const leaderboardTotalDownloads/)
  assert.match(adminService, /leaderboardDownloadsByShare\.slice\(0, 38\)/)
  assert.match(adminService, /findRecentActiveEmployeeDownloads\(prisma, downloadWhere, pageSize, skip\)/)
  assert.match(adminService, /findFirstActiveEmployeeDownloads\(prisma, downloadWhere\)/)
  assert.match(adminService, /const first38Winners = firstDownloads/)
  assert.match(adminService, /seenReceiverEmployeeIds/)
  assert.match(adminService, /function getMockReferrerScore/)
  assert.match(adminService, /score:\s*getMockReferrerScore/)
  assert.doesNotMatch(adminService, /pointBalance/)
  assert.doesNotMatch(adminService, /function getDisplayVerificationStatus/)
  assert.doesNotMatch(adminService, /status:\s*getDisplayVerificationStatus/)
  assert.doesNotMatch(adminService, /getMockVerificationStatus/)
  assert.doesNotMatch(adminService, /verifiedReceiverIdSuffixes/)
  assert.doesNotMatch(adminService, /unverifiedReceiverIdSuffixes/)
  assert.match(adminService, /first38Users:\s*topPioneers\.length/)
  assert.match(adminService, /first38Winners/)
  assert.match(adminService, /export async function getAdminDownloadsCsv/)
  assert.match(adminService, /findActiveEmployeeDownloadsForExport\(prisma, downloadWhere\)/)
  assert.match(adminService, /escapeCsvValue/)
  assert.match(repository, /findActiveEmployeeDownloadsForExport/)
  assert.match(repository, /findFirstActiveEmployeeDownloads/)
  assert.match(adminService, /skip = \(page - 1\) \* pageSize/)
  assert.match(adminService, /downloadedAt:\s*download\.createdAt\.toISOString\(\)/)
  assert.doesNotMatch(adminPage, /John Doe/)
  assert.doesNotMatch(adminPage, /FGF-JD88/)
})
